spring.application.name=todo

# Database configurarion

# TODO: ADD REAL DATABASE URL, USERNAME AND PASSWORD
spring.datasource.url=jdbc:postgresql://localhost:5433/todo
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

# spring doc configuration

springdoc.api-docs.enabled=true

# JWT Config

jwt.secret=OFriV2ngw2HJaNgUs6ahDEsNKz6ZoyPtO3LVvR68s5I=

# Server Configuration

server.port=8080
spring.main.banner-mode=off
